### ISSUE TITLE
Display resources

### ISSUE THREAD

**Issue by nitashadhingra** [Spiral-Forge/Protege-Web#5]
Resource page (Tab in the left vertical navbar)

1. one page that displays 6 categories on clicking on tab (3 per row on laptop, 2 or 1(whichever looks cleaner) per row in phone)
2. another page that has a list of resources under a particular category: 
       a. Title
       b. link 
       c. an upvote/downvote button for each resource
<img width="228" alt="Screenshot 2021-10-15 at 9 28 04 PM" src="https://user-images.githubusercontent.com/44186440/137517528-51dfaf19-9e4d-40a2-8b7e-e0b9cf114fb3.png">

**Comment by devanshi-katyal** [comment]
please assign the issue.

**Comment by nitashadhingra** [comment]
Read categories of resources dynamically from new database
